### ISSUE TITLE
nix build fail, hash mismatch

### ISSUE THREAD

**Issue by Genlight** [lorenzleutgeb/atlas#5]
Hi, 
I treid to install ATLAS via the nix framework and followed your instructions. 

Everything seemed okay until i did a build attempt with `nix build .`

here is my output

```
master@Dell:~/atlas$ nix build .
warning: Git tree '/home/master/atlas' is dirty
error: hash mismatch in fixed-output derivation '/nix/store/qacm1sqyxgzh2bvxfnkwb8yiz5xfzql4-jackson-parent-2.12.pom.drv':
         specified: sha256-Z749r6r4zhcX56fefbkrpDPfkjtpekDJdDpUzJ/FNjc=
            got:    sha256-YqocFnmt4J8XPb8bbDLTXFXnWAAjj9XkjxOqQzfAh1s=
error: 1 dependencies of derivation '/nix/store/bh7gs7v63pz6s2g0x5vr4x9q96g5473p-jackson-parent-2.12.pom.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jbg72qy7hnyx3yk6lxarx9k11xa7qlg1-atlas-gradle-plugin-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/wn1zbzgk5wgxx30mcip347d0danhhzxd-init.gradle.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ny9hym3ydgrwq4mq22k8yak9haznvmh9-atlas-0.1.4.drv' failed to build
```

Further, i tried to clean all nix-caches and redo the whole build process again with the same result. 

What i got from this error is that some providers with the nix package world are not consistent how they provide their hashes. Further there are differences between the same artifacts but taken from different resources. 

My question is now, do you already have this issue on the radar or not?

BR

**Comment by lorenzleutgeb** [comment]
Thanks for your report. Are you on `f091b2b` (head of `main` as of today)?

**Comment by lorenzleutgeb** [comment]
Please try again on `b34f3b4` (current head of `main`). Thanks for your patience.

**Comment by Genlight** [comment]
yes, that solved it. Thank you for your fast reply and fix.
